
{ expect } = require('chai')

{ Slowcopy } = require './../index.coffee'

{ makeFileOfSizeInMBytes, makeFileOfSizeInMBytesUnlessFileExists, verifyTwoFilesAreTheSame } = require './lib/test-utils.coffee'

describe 'Slowcopy', ->

  it 'Work in progress', (done)->
    @timeout 5000

    inputFilePath = './test/sample-files/dummy_autogenerated_1_30mb.file'

    outputFilePath = './test/sample-files/dummy_autogenerated_1_30mb_output.file'

    makeFileOfSizeInMBytesUnlessFileExists inputFilePath, 30, ->

      sc = new Slowcopy inputFilePath, outputFilePath, 1

      sc.on 'end', ->
        verifyTwoFilesAreTheSame inputFilePath, outputFilePath, (areTheySame)->
          expect(areTheySame).to.equal.true

          fs.unlinkSync inputFilePath
          fs.unlinkSync outputFilePath
          done()

      sc.copy()





