
{ expect } = require('chai')

{ Slowcopy } = require './../index.coffee'

{ makeFileOfSizeInMBytes, verifyTwoFilesAreTheSame } = require './lib/test-utils.coffee'

describe 'Slowcopy', ->

  it 'Work in progress', (done)->
    @timeout 5000

    inputFilePath = './test/sample-files/dummy_autogenerated_1.file'

    outputFilePath = './test/sample-files/dummy_autogenerated_1_output.file'

    makeFileOfSizeInMBytes inputFilePath, 30, ->

      sc = new Slowcopy inputFilePath, outputFilePath, 1

      sc.on 'end', ->
        verifyTwoFilesAreTheSame inputFilePath, outputFilePath, (areTheySame)->
          expect(areTheySame).to.equal.true
          done()

      sc.copy()





